### ISSUE TITLE
Dynamic scripts containing const and let variables are not exposed as global

### ISSUE THREAD

**Issue by Meir017** [webrecorder/wombat#82] opened 2022-05-13 12:50 UTC
consider a website defines some global variables
```js
const script1 = document.createElement('script');
script1.textContent = `const constGlobal = window;
let letGlobal = window;`;
document.body.appendChild(script1);

const script2 = document.createElement('script');
script2.textContent = `console.info("constGlobal", constGlobal);
console.info("letGlobal", letGlobal);`;
document.body.appendChild(script2);
```

the first script's code is rewritten to 
```js
var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
let window = _____WB$wombat$assign$function_____("window");
let self = _____WB$wombat$assign$function_____("self");
let document = _____WB$wombat$assign$function_____("document");
let location = _____WB$wombat$assign$function_____("location");
let top = _____WB$wombat$assign$function_____("top");
let parent = _____WB$wombat$assign$function_____("parent");
let frames = _____WB$wombat$assign$function_____("frames");
let opener = _____WB$wombat$assign$function_____("opener");
{
const constGlobal = window;
let letGlobal = window;

}}
```

due to the `constGlobal ` and `letGlobal ` not being defined in the global scope they do not exist outside of the scope they executed in
![image](https://user-images.githubusercontent.com/9786571/168286715-21110089-aff1-440b-aefe-ada10cc00758.png)

**Comment by ikreymer** [comment] 2022-05-20 00:54
You're right, unfortunately, there's not a solution for this currently :(

Fortunately, this doesn't happen too often in practice, as most sites don't use globals like this, and I think its sort of an anti-pattern.

I think it probably can't be solved with just lexical rewriting, probably need a JS parser to be able to detect this situation...

**Comment by mona-ul** [comment] 2023-06-22 11:54
## Description

I had the same issue a couple of times. JavaScript functions were't available in replay and error messages showed undefined variables. When taking a closer look, it showed that those variables were declared with const. 

For example:
live web: https://karen-everywhere.tumblr.com/
Pywb Replay (2.7.3): https://webarchives.rhizome.org/error_karen-everywhere_js_rewriting/20230125112330/https://karen-everywhere.tumblr.com/

The error occurs in Pywb and ReplayWeb.page.

## Expected behavior
1. Go to https://karen-everywhere.tumblr.com/
2. Click on green "stop" botton.
3. Pop-up opens

## What actually happened
1. Go to https://webarchives.rhizome.org/error_karen-everywhere_js_rewriting/20230125112330/https://karen-everywhere.tumblr.com/
2. Click on green "stop" botton.
3. Nothing happens

## Error Messages

```
Uncaught ReferenceError: toggleModal is not defined
```

## Workaround

For this object I managed to change the declaration of the variable without destroying any other functionality.

Steps:
- Identify JS file containing the declaration of the variables causing the issue.
- Get JS file
    - wget https://static.tumblr.com/kifah6n/1mTpyeq1p/rentsdue.min.js
- change declaration in JS file
    - const toggleModal=mid=>{$("#".concat(mid)).toggleClass("show-modal")}
    - → window.toggleModal=mid=>{$("#".concat(mid)).toggleClass("show-modal")}
- create WARC containing JS file
    - warcit https://static.tumblr.com/kifah6n/1mTpyeq1p/ rentsdue.min.js 
- add WARC to collection
- remove original JS file from collection

Workaround, Pywb Replay (2.7.3): https://webarchives.rhizome.org/Q15390/20230111102538/https://karen-everywhere.tumblr.com/

**Comment by ikreymer** [comment] 2023-06-29 19:01
Using acorn parser to detect top-level globals using let and const seems fairly straightforward (see webrecorder/wabac.js#128).

For pywb, will need to use a similar js-parser-in-python, such as https://github.com/PiotrDabkowski/pyjsparser

I think that can solve this issue once and for all!

**Comment by ikreymer** [comment] 2023-07-06 03:48
The fix has been deployed on replayweb.page. If you have WARCs or WACZs files that have this issue, please try replay on latest replayweb.page to see if replay works now.

**Comment by ikreymer** [comment] 2023-07-28 16:04
Seems to be fixed in wabac.js / replayweb.page, will open separate issue for pywb.

**Closed by ikreymer** 2023-07-28 16:04 UTC

**Comment by mona-ul** [comment] 2023-10-05 11:49
Hello Ilya, Thank you very much.
I can confirm that it now works in ArchiveWeb.Page.
